doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
        server_version: '8.0.35'
        types:
            json: Doctrine\DBAL\Types\JsonType
        mapping_types:
            enum: string
            longtext: json

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        enable_lazy_ghost_objects: true
        entity_managers:
            default:
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                report_fields_where_declared: true
                mappings:
                    # Configuração para as suas entidades usando o driver Attribute
                    app_entities:
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: App\Entity
                        alias: App
                        is_bundle: false
                metadata_cache_driver:
                    type: 'pool'
                    pool: 'app.cache.doctrine'
                query_cache_driver:
                    type: 'pool'
                    pool: 'app.cache.doctrine'
                result_cache_driver:
                    type: 'pool'
                    pool: 'app.cache.doctrine'

when@test:
    doctrine:
        dbal:
            dbname: '%database_name%_test'
