doctrine:
    dbal:
        driver: pdo_mysql
        url: '%env(DATABASE_URL)%'  # Utilizando a variável de ambiente DATABASE_URL
        server_version: '8.0'
        charset: utf8mb4
        logging: '%kernel.debug%'
