version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ops/docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "81:80"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://user:password@db:3306/dbname
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
