version: '3.9'

services:
  app:
    build: ./ops/docker
    image: api-adv:latest 
    volumes:
      - ./:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "82:80"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://user:password@db:3306/dbname
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./ops/docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_mvc
      MYSQL_USER: php_mvc
      MYSQL_PASSWORD: php_mvc  

volumes:
  mysql-data:
