version: '3.8'

services:
  app:
    build: ./ops/docker
    image: api-adv:latest
    volumes:
      - ./:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "82:80"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:password@db:3306/apiadv?serverVersion=8.0&charset=utf8mb4
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3306:3306"  # Corrigido para garantir acesso ao MySQL
    environment:
      MYSQL_ROOT_PASSWORD: password  # Definindo a senha do root
      MYSQL_DATABASE: apiadv  # Nome do banco de dados a ser criado
    volumes:
      - mysql-data:/var/lib/mysql  # Persistência de dados

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - db

volumes:
  mysql-data:
