services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    app.cache.doctrine:
        class: Symfony\Component\Cache\Adapter\ArrayAdapter
        arguments:
            - 3600 # Tempo de vida do cache em segundos
            - true # Resetar o cache ao inicializar

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\Client\ApiClient:
        arguments:
            $apiKey: '%api_key%'
            $baseUrl: '%base_url%'

    GuzzleHttp\Client:
        class: GuzzleHttp\Client
    
imports:
    - { resource: parameters.yaml }
