services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    GuzzleHttp\Client:
        class: GuzzleHttp\Client

imports:
    - { resource: parameters.yaml }
