services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\Client\ApiClient:
        arguments:
            $apiKey: '%api_key%'
            $baseUrl: '%base_url%'

    GuzzleHttp\Client:
        class: GuzzleHttp\Client

imports:
    - { resource: parameters.yaml }
